import{storage}from'../core/storage.js';import{median,pct}from'../utils/statistics.js';
export async function renderAnalytics(){
 const view=document.querySelector('#view');document.querySelector('#page-title').textContent='Progress Analytics';document.querySelector('#page-eyebrow').textContent='ACTIONABLE PERFORMANCE SIGNALS';
 let a=[];try{a=await storage.getAll('attempts')}catch(e){console.error(e)}
 const valid=a.filter(x=>Number.isFinite(x.responseMs)),correct=a.filter(x=>x.correct).length;
 const recent=[...a].sort((x,y)=>new Date(y.timestamp||y.createdAt||0)-new Date(x.timestamp||x.createdAt||0)).slice(0,20);
 const recentCorrect=recent.filter(x=>x.correct).length;
 const bySkill={};a.forEach(x=>(x.skills||[x.skill]).filter(Boolean).forEach(s=>{bySkill[s]??={n:0,c:0,t:[]};bySkill[s].n++;if(x.correct)bySkill[s].c++;if(Number.isFinite(x.responseMs))bySkill[s].t.push(x.responseMs)}));
 view.innerHTML=`<section class="section"><div class="grid grid-4"><div class="card metric"><span class="muted">Lifetime accuracy</span><strong>${pct(correct,a.length)}%</strong><small>${a.length} attempts</small></div><div class="card metric"><span class="muted">Recent accuracy</span><strong>${pct(recentCorrect,recent.length)}%</strong><small>Last ${recent.length} attempts</small></div><div class="card metric"><span class="muted">Median response</span><strong>${valid.length?(median(valid.map(x=>x.responseMs))/1000).toFixed(1)+'s':'–'}</strong><small>Median resists extreme pauses</small></div><div class="card metric"><span class="muted">Tracked skills</span><strong>${Object.keys(bySkill).length}</strong><small>With attempt evidence</small></div></div></section>
 <section class="section"><div class="card"><p class="eyebrow">BY SKILL</p><h2>Where performance changes</h2>${Object.keys(bySkill).length?`<div class="stack">${Object.entries(bySkill).sort((a,b)=>pct(a[1].c,a[1].n)-pct(b[1].c,b[1].n)).map(([s,v])=>`<div class="list-item"><span>${s.replaceAll('_',' ')}</span><strong>${pct(v.c,v.n)}% · ${v.t.length?(median(v.t)/1000).toFixed(1)+'s':'–'}</strong></div>`).join('')}</div>`:'<p class="muted">No attempt evidence yet.</p>'}</div></section>`;
}