export class ExamBoard{
 constructor(root,{entities,slots,onChange=()=>{}}){this.root=root;this.entities=entities;this.slots=slots;this.onChange=onChange;this.placements={};this.states={};this.selected=null;this.history=[];this.future=[];this.render()}
 snapshot(){return{placements:{...this.placements},states:{...this.states}}}
 save(){this.history.push(this.snapshot());if(this.history.length>60)this.history.shift();this.future=[]}
 restore(s){this.placements={...s.placements};this.states={...s.states};this.selected=null;this.render();this.onChange(this.snapshot())}
 undo(){if(!this.history.length)return;this.future.push(this.snapshot());this.restore(this.history.pop())}
 redo(){if(!this.future.length)return;this.history.push(this.snapshot());this.restore(this.future.pop())}
 reset(){this.save();this.placements={};this.states={};this.selected=null;this.render();this.onChange(this.snapshot())}
 toggleState(entity){if(!Number.isInteger(this.placements[entity]))return;this.save();this.states[entity]=this.states[entity]==='confirmed'?'tentative':'confirmed';this.render();this.onChange(this.snapshot())}
 place(entity,pos){this.save();for(const [e,p] of Object.entries(this.placements))if(p===pos)delete this.placements[e];this.placements[entity]=pos;if(!this.states[entity])this.states[entity]='tentative';this.selected=null;this.render();this.onChange(this.snapshot())}
 remove(entity){if(!Number.isInteger(this.placements[entity]))return;this.save();delete this.placements[entity];delete this.states[entity];this.render();this.onChange(this.snapshot())}
 render(){this.root.innerHTML=`<div class="exam-token-bank">${this.entities.map(e=>`<button class="exam-token ${this.selected===e?'selected':''} ${this.states[e]||''}" data-token="${e}">${e}<small>${this.states[e]==='confirmed'?'Confirmed':Number.isInteger(this.placements[e])?'Tentative':'Unplaced'}</small></button>`).join('')}</div><div class="exam-slots">${Array.from({length:this.slots},(_,i)=>{const e=Object.keys(this.placements).find(k=>this.placements[k]===i);return`<button class="exam-slot ${e?this.states[e]||'tentative':''}" data-slot="${i}">${e?`<b>${e}</b>`:'<em>Place</em>'}</button>`}).join('')}</div><div class="board-toolbar"><button class="button ghost" id="undo-b">Undo</button><button class="button ghost" id="redo-b">Redo</button><button class="button ghost" id="reset-b">Reset</button><span class="muted">Select any person above, then choose an empty position to place or move it. Click a placed board position to toggle Tentative ↔ Confirmed</span></div>`;
 this.root.querySelectorAll('[data-token]').forEach(b=>b.onclick=()=>{const e=b.dataset.token;this.selected=this.selected===e?null:e;this.render()});
 this.root.querySelectorAll('[data-slot]').forEach(b=>b.onclick=()=>{const pos=+b.dataset.slot;const occupant=Object.keys(this.placements).find(e=>this.placements[e]===pos);if(this.selected){if(!occupant||occupant===this.selected)this.place(this.selected,pos);return}if(occupant)this.toggleState(occupant)});
 this.root.querySelector('#undo-b').onclick=()=>this.undo();this.root.querySelector('#redo-b').onclick=()=>this.redo();this.root.querySelector('#reset-b').onclick=()=>this.reset()}
}