import{CircularBoard}from'../components/circular-board.js';
import{validateCircularArrangement,answerCircularQuestion}from'../engines/circular-engine.js';
import{preflightCircularPuzzle}from'../engines/circular-preflight.js';
const KEY='reasonforge.circular.v10.4.progress';
const getProgress=()=>{try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return{}}};
export async function renderCircularLab(){
 const view=document.querySelector('#view');document.querySelector('#page-title').textContent='Circular Mastery';document.querySelector('#page-eyebrow').textContent='V10.4 · 40-PUZZLE PRACTICE BANK';
 view.innerHTML='<div class="card empty-state">Loading validated practice bank…</div>';
 try{
  const r=await fetch('./data/puzzles/circular.json');if(!r.ok)throw new Error(`Data load failed (${r.status})`);const all=await r.json();
  const bad=all.find(p=>!preflightCircularPuzzle(p).valid);if(bad)throw new Error(`Preflight failed: ${bad.id}`);
  let mode='mixed',difficulty='All',index=0,progress=getProgress();
  const list=()=>all.filter(p=>p.mode===mode&&(difficulty==='All'||p.difficulty===difficulty));
  const draw=()=>{
   const items=list();index=(index+items.length)%items.length;const p=items[index],solved=!!progress[p.id],solvedCount=all.filter(x=>progress[x.id]).length;
   const rule=p.facing==='center'?'Left → clockwise · Right → anticlockwise':p.facing==='outside'?'Left → anticlockwise · Right → clockwise':'Direction follows the reference person’s facing';
   view.innerHTML=`<section class="rf-circular-page">
   <div class="rf-v10-hero"><div><p class="eyebrow">V10.4 CONTENT QUALITY FOUNDATION</p><h2>40 validated practice puzzles</h2><p>Unique solutions, non-redundant positional clue graphs, difficulty progression, and saved practice progress.</p></div><div class="rf-v10-badge">10.4</div></div>
   <div class="rf-bank-toolbar"><div class="rf-mode-tabs">${['center','outside','mixed'].map(m=>`<button class="rf-mode-tab ${m===mode?'active':''}" data-mode="${m}"><strong>${m==='center'?'Center Facing':m==='outside'?'Outside Facing':'Mixed Facing'}</strong><small>${all.filter(x=>x.mode===m).length} puzzles</small></button>`).join('')}</div><div class="rf-bank-controls"><label>Difficulty <select id="rf-difficulty">${['All','Foundation','Standard','PO Prelims','Hard PO Prelims'].map(d=>`<option ${d===difficulty?'selected':''}>${d}</option>`).join('')}</select></label><span class="rf-progress-pill">${solvedCount}/40 solved</span></div></div>
   <div class="rf-puzzle-meta"><div><span>${p.difficulty}</span><strong>${p.title}</strong></div><div><span>Puzzle ${index+1} of ${items.length}</span><span>Quality ${p.qualityScore}/100</span>${solved?'<span class="is-solved">✓ Solved</span>':''}</div></div>
   <div class="rf-direction-card rf-v10-rule"><span>DIRECTION RULE</span><strong>${p.facing==='mixed'?'Reference-person logic':`Facing ${p.facing}`}</strong><p>${rule}</p></div>
   <div class="rf-circular-layout"><aside class="rf-clue-panel"><div class="rf-panel-heading"><p class="eyebrow">${p.mode.toUpperCase()} · ${p.difficulty.toUpperCase()}</p><h3>Build the arrangement</h3></div><ol class="rf-clue-list">${p.clues.map((c,i)=>`<li data-clue-id="${c.id}"><span>${i+1}</span><p>${c.text}</p></li>`).join('')}</ol></aside><main class="rf-workspace-panel"><div class="rf-panel-heading"><p class="eyebrow">WORKSPACE</p><h3>Build the complete arrangement</h3></div><div id="rf-circular-board"></div><div class="rf-check-row"><button class="button" id="rf-check-arrangement">Check arrangement</button><div id="rf-arrangement-feedback" class="feedback" hidden></div></div></main></div>
   <div class="rf-puzzle-nav"><button class="button ghost" id="rf-prev">← Previous</button><button class="button ghost" id="rf-random">Random puzzle</button><button class="button secondary" id="rf-next">Next →</button></div>
   <section class="rf-transfer-panel"><div class="rf-panel-heading"><p class="eyebrow">TRANSFER QUESTIONS</p><h3>Read relationships from your arrangement</h3></div><div class="rf-question-grid">${p.questions.map((q,i)=>`<label class="rf-question-card"><span class="rf-question-number">0${i+1}</span><strong>${q.prompt}</strong><select data-rf-question="${i}"><option value="">Choose person</option>${p.entities.map(e=>`<option value="${e}">${e}</option>`).join('')}</select></label>`).join('')}</div><div class="rf-check-row"><button class="button secondary" id="rf-check-questions">Check answers</button><div id="rf-question-feedback" class="feedback" hidden></div></div></section></section>`;
   view.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{mode=b.dataset.mode;difficulty='All';index=0;draw()});view.querySelector('#rf-difficulty').onchange=e=>{difficulty=e.target.value;index=0;draw()};
   view.querySelector('#rf-prev').onclick=()=>{index--;draw()};view.querySelector('#rf-next').onclick=()=>{index++;draw()};view.querySelector('#rf-random').onclick=()=>{if(items.length>1){let j=index;while(j===index)j=Math.floor(Math.random()*items.length);index=j}draw()};
   const board=new CircularBoard(view.querySelector('#rf-circular-board'),{entities:p.entities,mode:p.mode});
   view.querySelector('#rf-check-arrangement').onclick=()=>{const f=view.querySelector('#rf-arrangement-feedback');f.hidden=false;if(Object.keys(board.placements).length!==p.entities.length){f.className='feedback warning';f.textContent='Place every person before validating.';return}const x=validateCircularArrangement(board.placements,p,board.facings);board.clearHighlights();f.className=`feedback ${x.valid?'success':'error'} rf-explainable-feedback`;if(x.valid){progress[p.id]=true;localStorage.setItem(KEY,JSON.stringify(progress));f.innerHTML='<strong>Perfect arrangement</strong><span>All constraints satisfied. Progress saved.</span>'}else{const e=x.failures[0];board.setHighlights(e.people);view.querySelectorAll('.rf-clue-list li').forEach(li=>li.classList.remove('is-clue-error'));const item=view.querySelector(`[data-clue-id="${e.sourceClueId}"]`);if(item)item.classList.add('is-clue-error');f.innerHTML=`<div class="rf-error-head"><strong>${x.positionFailures.length} POSITION · ${x.facingFailures.length} FACING ERROR${x.failures.length!==1?'S':''}</strong><span>${e.title}</span></div><div class="rf-error-clue">“${e.clueText}”</div><div class="rf-error-detail">${e.detail}</div><div class="rf-error-rule">${e.rule}</div>`}};
   view.querySelector('#rf-check-questions').onclick=()=>{const f=view.querySelector('#rf-question-feedback');f.hidden=false;if(Object.keys(board.placements).length!==p.entities.length){f.className='feedback warning';f.textContent='Complete the arrangement first.';return}let c=0,a=0;view.querySelectorAll('[data-rf-question]').forEach(s=>{if(s.value)a++;const q=p.questions[+s.dataset.rfQuestion];if(s.value===answerCircularQuestion(q,p,board.placements,board.facings))c++});f.className=`feedback ${c===p.questions.length?'success':'warning'}`;f.textContent=a<p.questions.length?`Answer all questions. ${c} correct so far.`:`${c}/${p.questions.length} transfer answers correct.`};
  };draw();
 }catch(e){console.error(e);view.innerHTML=`<div class="card empty-state"><h2>Circular Mastery could not load</h2><p>${e.message}</p></div>`}
}