import{storage}from'../core/storage.js';
const TASKS=[
 {id:'scan',title:'Rapid Scan',instruction:'Find the only pair that breaks the pattern.',build(){const base=['AB','CD','EF','GH','IJ','KL','MN','OP'];const bad=Math.floor(Math.random()*base.length);const items=base.map((x,i)=>i===bad?x[1]+x[0]:x);return{prompt:'Select the reversed pair.',options:items,answer:items[bad]}}},
 {id:'update',title:'Mental Position Update',instruction:'Track the person without drawing a full board.',build(){const names=['A','B','C','D','E'];const shifts=[2,-1,3,-2];let pos=2;for(const s of shifts)pos=(pos+s+5)%5;return{prompt:`${names.join('  ')} start left to right. Track C: move 2 right, 1 left, 3 right, then 2 left. Where does C finish?`,options:['1st','2nd','3rd','4th','5th'],answer:`${['1st','2nd','3rd','4th','5th'][pos]}`}}},
 {id:'memory',title:'Constraint Memory',instruction:'Hold the chain, then infer the final relation.',build(){return{prompt:'B is second right of A. C is immediately left of B. D is third right of C. Where is D relative to A?',options:['2 left','1 right','2 right','4 right'],answer:'4 right'}}}
];
let state;
export async function renderCognitiveWarmup(){
 document.querySelector('#page-title').textContent='Cognitive Warm-Up';document.querySelector('#page-eyebrow').textContent='3-MINUTE REASONING PRIMER';
 state={index:0,correct:0,started:performance.now(),items:TASKS.map(t=>({...t,round:t.build()}))};draw();
}
function draw(){const view=document.querySelector('#view'),t=state.items[state.index],r=t.round;view.innerHTML=`<section class="training-card"><div class="session-progress"><div class="progress-track"><span style="width:${state.index/state.items.length*100}%"></span></div><strong>${state.index+1}/${state.items.length}</strong></div><div class="card warmup-card"><p class="eyebrow">${t.title.toUpperCase()}</p><h2>${t.instruction}</h2><p class="warmup-prompt">${r.prompt}</p><div class="answer-grid">${r.options.map(o=>`<button class="answer-option" data-answer="${o}">${o}</button>`).join('')}</div><div id="warmup-feedback"></div></div></section>`;view.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>answer(b.dataset.answer));}
function answer(value){const t=state.items[state.index],ok=value===t.round.answer,fb=document.querySelector('#warmup-feedback');document.querySelectorAll('[data-answer]').forEach(b=>{b.disabled=true;b.classList.toggle('selected',b.dataset.answer===value)});if(ok)state.correct++;fb.innerHTML=`<div class="feedback ${ok?'success':'error'}"><strong>${ok?'Correct.':'Not quite.'}</strong><p>Answer: ${t.round.answer}</p><button class="button" id="warmup-next">${state.index===state.items.length-1?'Finish warm-up':'Next drill'}</button></div>`;document.querySelector('#warmup-next').onclick=next;}
async function next(){state.index++;if(state.index<state.items.length)return draw();const ms=Math.round(performance.now()-state.started);try{await storage.put('sessions',{id:crypto.randomUUID(),type:'cognitive_warmup',startedAt:new Date(Date.now()-ms).toISOString(),endedAt:new Date().toISOString(),attempts:state.items.length,correct:state.correct})}catch{}document.querySelector('#view').innerHTML=`<section class="training-card"><div class="card empty-state"><p class="eyebrow">WARM-UP COMPLETE</p><div class="summary-score">${Math.round(state.correct/state.items.length*100)}%</div><h2>${state.correct}/${state.items.length} correct</h2><p>Completed in ${(ms/1000).toFixed(1)}s. Move into puzzle practice while the reasoning loop is active.</p></div><div class="hero-actions"><button class="button" id="warmup-puzzles">Start Full PO Puzzles</button><button class="button secondary" id="warmup-again">Repeat warm-up</button></div></section>`;document.querySelector('#warmup-puzzles').onclick=()=>location.hash='full-po-puzzles';document.querySelector('#warmup-again').onclick=renderCognitiveWarmup;}
